
# Add labels the plugin from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Pixel classification
  - Object classification
  - Image annotation
  - Image feature detection
